apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xapp-auth
rules:
  - apiGroups: [ "metrics.k8s.io" ]
    resources: [ "nodes" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "watch", "list", "create", "delete" ]
