apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xapp-permission
subjects:
  - kind: User
    name: system:serviceaccount:ricxapp:default
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: xapp-auth
  apiGroup: rbac.authorization.k8s.io
